CREATE TABLE moto
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tag_rfid  VARCHAR(255)                            NOT NULL,
    cor       VARCHAR(255),
    modelo    VARCHAR(255),
    latitude  DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    CONSTRAINT pk_moto PRIMARY KEY (id)
);

ALTER TABLE moto
    ADD CONSTRAINT uc_moto_tagrfid UNIQUE (tag_rfid);